name: Build and Push Docker Image

on:
  push:
    tags:
      - '*.*.*'
env:
  ALICLOUD_USERNAME: 个人号
  NAMESPACE: qcq-wxl
  IMAGE_NAME: miner_fe
  TAG_NAME: latest

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v3

      - name: Log in to Alibaba Cloud Container Registry
        run: echo ${{ secrets.ALICLOUD_PASSWORD }} | docker login --username ${{ env.ALICLOUD_USERNAME }} --password-stdin registry.cn-hangzhou.aliyuncs.com

#      - name: Extract tag name
#        id: extract_tag
#        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build and push Docker image
        run: |
          docker build -t registry.cn-hangzhou.aliyuncs.com/${{ env.NAMESPACE }}/${{ env.IMAGE_NAME }}:${{ env.TAG_NAME }} .
          docker push registry.cn-hangzhou.aliyuncs.com/${{ env.NAMESPACE }}/${{ env.IMAGE_NAME }}:${{ env.TAG_NAME }}
